name: Rollback to tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag from tagDatabase'
        required: true
        type: string

jobs:
  rollback-db:
    name: "Rollback DB"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
     - uses: actions/checkout@v4
     - uses: liquibase-github-actions/rollback-sql@v4.31.1
       with:
        changelogFile: "root-changelog.yaml"
        tag: ${{ github.event.inputs.tag }}
        url: ${{ vars.DB_JDBC_URL }}
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        headless: true
        logLevel: INFO
     - uses: liquibase-github-actions/rollback@v4.31.1
       with:
        changelogFile: "root-changelog.yaml"
        tag: ${{ github.event.inputs.tag }}
        url: ${{ vars.DB_JDBC_URL }}
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        headless: true
        logLevel: INFO